using System.Collections.Generic;

namespace TappedKeyDisplay
{
    internal class VirtualCodeToKeyboardKey
    {
        Dictionary<int, string> keyDict = new Dictionary<int, string>();

        public void Init()
        {
            keyDict.Add(1, "Left mouse button");
            keyDict.Add(2, "Right mouse button");
            keyDict.Add(3, "Control-break processing");
            keyDict.Add(4, "Middle mouse button");
            keyDict.Add(5, "X1 mouse button");
            keyDict.Add(6, "X2 mouse button");
            keyDict.Add(7, "Undefined");
            keyDict.Add(8, "Backspace");
            keyDict.Add(9, "Tab");
            keyDict.Add(12, "Clear");
            keyDict.Add(13, "Enter");
            keyDict.Add(16, "Shift");
            keyDict.Add(17, "Ctrl");
            keyDict.Add(18, "Alt");
            keyDict.Add(19, "Pause");
            keyDict.Add(20, "Caps Lock");
            keyDict.Add(27, "Esc");
            keyDict.Add(32, " ");
            keyDict.Add(33, "Page Up");
            keyDict.Add(34, "Page Down");
            keyDict.Add(35, "End");
            keyDict.Add(36, "Home");
            keyDict.Add(37, "←");
            keyDict.Add(38, "↑");
            keyDict.Add(39, "→");
            keyDict.Add(40, "↓");
            keyDict.Add(41, "Select");
            keyDict.Add(42, "Print");
            keyDict.Add(43, "Execute");
            keyDict.Add(44, "Print Screen");
            keyDict.Add(45, "Insert");
            keyDict.Add(46, "Delete");
            keyDict.Add(47, "Help");
            keyDict.Add(48, "0");
            keyDict.Add(49, "1");
            keyDict.Add(50, "2");
            keyDict.Add(51, "3");
            keyDict.Add(52, "4");
            keyDict.Add(53, "5");
            keyDict.Add(54, "6");
            keyDict.Add(55, "7");
            keyDict.Add(56, "8");
            keyDict.Add(57, "9");
            keyDict.Add(65, "A");
            keyDict.Add(66, "B");
            keyDict.Add(67, "C");
            keyDict.Add(68, "D");
            keyDict.Add(69, "E");
            keyDict.Add(70, "F");
            keyDict.Add(71, "G");
            keyDict.Add(72, "H");
            keyDict.Add(73, "I");
            keyDict.Add(74, "J");
            keyDict.Add(75, "K");
            keyDict.Add(76, "L");
            keyDict.Add(77, "M");
            keyDict.Add(78, "N");
            keyDict.Add(79, "O");
            keyDict.Add(80, "P");
            keyDict.Add(81, "Q");
            keyDict.Add(82, "R");
            keyDict.Add(83, "S");
            keyDict.Add(84, "T");
            keyDict.Add(85, "U");
            keyDict.Add(86, "V");
            keyDict.Add(87, "W");
            keyDict.Add(88, "X");
            keyDict.Add(89, "Y");
            keyDict.Add(90, "Z");
            keyDict.Add(91, "Left Windows");
            keyDict.Add(92, "Right Windows");
            keyDict.Add(93, "Applications");
            keyDict.Add(95, "Computer Sleep");
            keyDict.Add(96, "0");
            keyDict.Add(97, "1");
            keyDict.Add(98, "2");
            keyDict.Add(99, "3");
            keyDict.Add(100, "4");
            keyDict.Add(101, "5");
            keyDict.Add(102, "6");
            keyDict.Add(103, "7");
            keyDict.Add(104, "8");
            keyDict.Add(105, "9");
            keyDict.Add(106, "*");
            keyDict.Add(107, "+");
            keyDict.Add(108, "|");
            keyDict.Add(109, "-");
            keyDict.Add(110, ".");
            keyDict.Add(111, "/");
            keyDict.Add(112, "F1");
            keyDict.Add(113, "F2");
            keyDict.Add(114, "F3");
            keyDict.Add(115, "F4");
            keyDict.Add(116, "F5");
            keyDict.Add(117, "F6");
            keyDict.Add(118, "F7");
            keyDict.Add(119, "F8");
            keyDict.Add(120, "F9");
            keyDict.Add(121, "F10");
            keyDict.Add(122, "F11");
            keyDict.Add(123, "F12");
            keyDict.Add(124, "F13");
            keyDict.Add(125, "F14");
            keyDict.Add(126, "F15");
            keyDict.Add(127, "F16");
            keyDict.Add(128, "F17");
            keyDict.Add(129, "F18");
            keyDict.Add(130, "F19");
            keyDict.Add(131, "F20");
            keyDict.Add(132, "F21");
            keyDict.Add(133, "F22");
            keyDict.Add(134, "F23");
            keyDict.Add(135, "F24");
            keyDict.Add(144, "Num Lock");
            keyDict.Add(145, "Scroll Lock");
            keyDict.Add(160, "L.Shift");
            keyDict.Add(161, "R.Shift");
            keyDict.Add(162, "L.Ctrl");
            keyDict.Add(163, "R.Ctrl");
            keyDict.Add(164, "L.Alt");
            keyDict.Add(165, "R.Alt");
            keyDict.Add(173, "Volume Mute");
            keyDict.Add(174, "Volume Down");
            keyDict.Add(175, "Volume Up");
            keyDict.Add(176, "Next Track");
            keyDict.Add(177, "Previous Track");
            keyDict.Add(178, "Stop Media");
            keyDict.Add(179, "Play/Pause Media");
            keyDict.Add(180, "Start Mail");
            keyDict.Add(181, "Select Media");
            keyDict.Add(182, "Start Application 1");
            keyDict.Add(183, "Start Application 2");
            keyDict.Add(186, ";");
            keyDict.Add(187, "+");
            keyDict.Add(188, ",");
            keyDict.Add(189, "-");
            keyDict.Add(190, ".");
            keyDict.Add(191, "/");
            keyDict.Add(192, "~");
            keyDict.Add(219, "[");
            keyDict.Add(220, "\\");
            keyDict.Add(221, "]");
            keyDict.Add(222, "'");
            keyDict.Add(246, "Attn");
            keyDict.Add(247, "CrSel");
            keyDict.Add(248, "ExSel");
            keyDict.Add(249, "Erase EOF");
            keyDict.Add(250, "Play");
            keyDict.Add(251, "Zoom");
            keyDict.Add(253, "PA1");
            keyDict.Add(254, "Clear");
        }

        public string vc2key(int vc)
        {
            return keyDict[vc];
        }
    }
}
